version: 2.1
jobs:
  test:
    trigger-new-pipeline:
          docker: 
            - image: cimg/base:2021.11
          resource_class: small
          steps:
            - run:
                name: Branch
                command: echo "${CIRCLE_BRANCH}", "${PIPELINE_GIT_TAG}"
            - run:
                name: Ping another pipeline
                command: |
                  curl --request POST \
                    --url https://circleci.com/api/v2/project/github/Pavithra137/WebApp/pipeline \
                    --header "Circle-Token: $CIRCLECI_API_KEY" \
                    --header "content-type: application/json" \
                    --data '{"branch":"main","parameters":{"image-name":"'$DOCKER_LOGIN"/"$CIRCLE_PROJECT_REPONAME":"0.1.<< pipeline.number >>'"}}'
